{
  "openapi": "3.0.0",
  "info": {
    "version": "4.0.0",
    "title": "Autosubmit API",
    "license": {
      "url": "https://www.gnu.org/licenses/gpl-3.0.html",
      "name": "GNU General Public License"
    }
  },
  "paths": {
    "/v3/login": {
      "post": {
        "tags": ["v3"],
        "summary": "Login",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/tokentest": {
      "get": {
        "tags": ["v3"],
        "summary": "Token test",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "post": {
        "tags": ["v3"],
        "summary": "Token test",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/updatedesc": {
      "get": {
        "tags": ["v3"],
        "summary": "Update description",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "post": {
        "tags": ["v3"],
        "summary": "Update description",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/cconfig/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get current configuration",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/expinfo/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment info",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/expcount/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment counters",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/searchowner/{owner}/{exptype}/{onlyactive}": {
      "get": {
        "tags": ["v3"],
        "summary": "Search owner",
        "parameters": [
          {
            "name": "owner",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "exptype",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "onlyactive",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/searchowner/{owner}": {
      "get": {
        "tags": ["v3"],
        "summary": "Search owner",
        "parameters": [
          {
            "name": "owner",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/search/{expid}/{exptype}/{onlyactive}": {
      "get": {
        "tags": ["v3"],
        "summary": "Search experiment",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "exptype",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "onlyactive",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/search/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Search experiment",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/running": {
      "get": {
        "tags": ["v3"],
        "summary": "Running experiments",
        "operationId": "get-v3-running",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "experiment": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "completed": {
                            "type": "integer"
                          },
                          "description": {
                            "type": "string"
                          },
                          "failed": {
                            "type": "integer"
                          },
                          "hpc": {
                            "type": "string"
                          },
                          "id": {
                            "type": "integer"
                          },
                          "modified": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "queuing": {
                            "type": "integer"
                          },
                          "running": {
                            "type": "integer"
                          },
                          "status": {
                            "type": "string"
                          },
                          "submitted": {
                            "type": "integer"
                          },
                          "suspended": {
                            "type": "integer"
                          },
                          "total": {
                            "type": "integer"
                          },
                          "user": {
                            "type": "string"
                          },
                          "version": {
                            "type": "string"
                          },
                          "wrapper": {
                            "type": "string",
                            "nullable": true
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "experiment": [
                        {
                          "completed": 25,
                          "description": "Testing AS 4.0",
                          "failed": 8,
                          "hpc": "MARENOSTRUM4",
                          "id": 8192,
                          "modified": "2022-10-03 10:05:27",
                          "name": "a4yd",
                          "queuing": 0,
                          "running": 0,
                          "status": "RUNNING",
                          "submitted": 0,
                          "suspended": 0,
                          "total": 385,
                          "user": "root",
                          "version": "4.0.0b0",
                          "wrapper": null
                        },
                        {
                          "completed": 88,
                          "description": "TEST_AS_4.0",
                          "failed": 0,
                          "hpc": "MARENOSTRUM4",
                          "id": 8202,
                          "modified": "2022-11-30 11:50:29",
                          "name": "t0an",
                          "queuing": 0,
                          "running": 0,
                          "status": "RUNNING",
                          "submitted": 0,
                          "suspended": 0,
                          "total": 91,
                          "user": "root",
                          "version": "4.0.0b0",
                          "wrapper": null
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v3/runs/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get runs",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/ifrun/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get if running",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/logrun/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get status and log path experiment",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/summary/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment summary",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/shutdown/{route}": {
      "get": {
        "tags": ["v3"],
        "summary": "Shutdown route",
        "parameters": [
          {
            "name": "route",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/performance/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment performance metrics",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/graph/{expid}/{layout}/{grouped}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get graph format",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "layout",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "grouped",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/tree/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment tree",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/quick/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get quick view data",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/exprun/{expid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment run log",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/joblog/{logfile}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get job log from path",
        "parameters": [
          {
            "name": "logfile",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/pklinfo/{expid}/{timeStamp}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment pklinfo",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "timeStamp",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/pkltreeinfo/{expid}/{timeStamp}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment tree pklinfo",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "timeStamp",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/stats/{expid}/{filter_period}/{filter_type}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment statistics",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter_period",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter_type",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/history/{expid}/{jobname}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment job history",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "jobname",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/rundetail/{expid}/{runid}": {
      "get": {
        "tags": ["v3"],
        "summary": "Get experiment run job detail",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "runid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v3/filestatus/": {
      "get": {
        "tags": ["v3"],
        "summary": "[LEGACY] Get file status",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/v4/experiments": {
      "get": {
        "tags": ["v4"],
        "summary": "Search experiments",
        "description": "",
        "operationId": "get-v4-experiments",
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "only_active",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "owner",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "exp_type",
            "in": "query",
            "schema": {
              "type": "string",
              "enum": ["test", "operational", "experiment"]
            }
          },
          {
            "name": "autosubmit_version",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "order_by",
            "in": "query",
            "schema": {
              "type": "string",
              "enum": ["expid", "created", "description"]
            }
          },
          {
            "name": "order_desc",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "page_size",
            "in": "query",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "experiments": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "completed": {
                            "type": "integer"
                          },
                          "description": {
                            "type": "string"
                          },
                          "failed": {
                            "type": "integer"
                          },
                          "hpc": {
                            "type": "string",
                            "nullable": true
                          },
                          "id": {
                            "type": "integer"
                          },
                          "modified": {
                            "type": "string",
                            "nullable": true
                          },
                          "name": {
                            "type": "string"
                          },
                          "queuing": {
                            "type": "integer"
                          },
                          "running": {
                            "type": "integer"
                          },
                          "status": {
                            "type": "string"
                          },
                          "submitted": {
                            "type": "integer"
                          },
                          "suspended": {
                            "type": "integer"
                          },
                          "total": {
                            "type": "integer"
                          },
                          "user": {
                            "type": "string",
                            "nullable": true
                          },
                          "version": {
                            "type": "string"
                          },
                          "wrapper": {
                            "type": "string",
                            "nullable": true
                          }
                        }
                      }
                    },
                    "pagination": {
                      "type": "object",
                      "properties": {
                        "page": {
                          "type": "integer"
                        },
                        "page_items": {
                          "type": "integer"
                        },
                        "page_size": {
                          "type": "integer"
                        },
                        "total_items": {
                          "type": "integer"
                        },
                        "total_pages": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "experiments": [
                        {
                          "completed": 0,
                          "description": "DE Model App",
                          "failed": 0,
                          "hpc": null,
                          "id": 9,
                          "modified": null,
                          "name": "a005",
                          "queuing": 0,
                          "running": 0,
                          "status": "NOT RUNNING",
                          "submitted": 0,
                          "suspended": 0,
                          "total": 0,
                          "user": null,
                          "version": "Unknown",
                          "wrapper": null
                        },
                        {
                          "completed": 115,
                          "description": "DE downstream",
                          "failed": 0,
                          "hpc": "LOCAL",
                          "id": 11,
                          "modified": "2023-10-26 11:44:07",
                          "name": "a006",
                          "queuing": 0,
                          "running": 0,
                          "status": "NOT RUNNING",
                          "submitted": 0,
                          "suspended": 0,
                          "total": 115,
                          "user": "ltenorio",
                          "version": "4.0.95",
                          "wrapper": null
                        }
                      ],
                      "pagination": {
                        "page": 1,
                        "page_items": 2,
                        "page_size": 2,
                        "total_items": 9,
                        "total_pages": 5
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v4/experiments/{expid}": {
      "get": {
        "tags": ["v4"],
        "summary": "Get experiment info",
        "operationId": "get-v4-experiments-expid",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/v4/experiments/{expid}/jobs": {
      "get": {
        "tags": ["v4"],
        "summary": "List experiment jobs",
        "operationId": "get-v4-experiments-expid-jobs",
        "parameters": [
          {
            "name": "view",
            "in": "query",
            "description": "Data view selector",
            "schema": {
              "type": "string",
              "enum": ["base", "quick"]
            }
          },
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "jobs": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Job"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "jobs": [
                        {
                          "name": "a008_20200120_fc0_2_SIM",
                          "status": "COMPLETED",
                          "priority": 4,
                          "section": "SIM",
                          "date": "2020-01-20T00:00:00",
                          "member": "fc0",
                          "chunk": 2,
                          "out_path_local": "a008_20200120_fc0_2_SIM.20231027153508.out",
                          "err_path_local": "a008_20200120_fc0_2_SIM.20231027153508.err",
                          "out_path_remote": "a008_20200120_fc0_2_SIM.20231027153508.out",
                          "err_path_remote": "a008_20200120_fc0_2_SIM.20231027153508.err"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v4/experiments/{expid}/wrappers": {
      "get": {
        "tags": ["v4"],
        "summary": "List experiment wrappers",
        "operationId": "get-v4-experiments-expid-wrappers",
        "parameters": [
          {
            "name": "expid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "wrappers": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "job_names": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          "wrapper_name": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v4/auth/verify-token": {
      "get": {
        "tags": ["v4"],
        "summary": "Verify JWT Token",
        "operationId": "get-v4-auth-verify-token",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "JWT Token",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "user": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": true,
                      "user": "username"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "user": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": false,
                      "user": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v4/auth/cas/v2/login": {
      "get": {
        "tags": ["v4"],
        "summary": "CAS v2 Login",
        "operationId": "get-v4-auth-cas-v2-login",
        "parameters": [
          {
            "name": "ticket",
            "in": "query",
            "description": "CAS ticket",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "service",
            "in": "query",
            "description": "CAS service",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    },
                    "user": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": true,
                      "message": "Token generated",
                      "token": "...",
                      "user": "username"
                    }
                  }
                }
              }
            }
          },
          "302": {
            "description": "Redirect to CAS login form"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string",
                      "nullable": true
                    },
                    "user": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": false,
                      "message": "Unauthorized",
                      "token": null,
                      "user": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v4/auth/oauth2/github/login": {
      "get": {
        "tags": ["v4"],
        "summary": "GitHub Oauth2 App Login",
        "operationId": "get-v4-auth-oauth2-github-login",
        "parameters": [
          {
            "name": "code",
            "in": "query",
            "description": "GitHub code used to exchange for an access_token",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    },
                    "user": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": true,
                      "message": "Token generated",
                      "token": "...",
                      "user": "username"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authenticated": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string",
                      "nullable": true
                    },
                    "user": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "authenticated": false,
                      "message": "Unauthorized",
                      "token": null,
                      "user": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Job": {
        "type": "object",
        "title": "Job",
        "description": "Base experiment job",
        "properties": {
          "name": {
            "type": "string",
            "description": "Job identifier"
          },
          "status": {
            "type": "string",
            "enum": [
              "WAITING",
              "READY",
              "SUBMITTED",
              "QUEUING",
              "RUNNING",
              "COMPLETED",
              "HELD",
              "PREPARED",
              "SKIPPED",
              "DELAYED",
              "FAILED",
              "UNKNOWN",
              "SUSPENDED"
            ],
            "description": "Status of the job",
            "default": "UNKNOWN"
          },
          "priority": {
            "type": "integer"
          },
          "section": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "member": {
            "type": "string"
          },
          "chunk": {
            "type": "integer"
          },
          "out_path_local": {
            "type": "string"
          },
          "err_path_local": {
            "type": "string"
          },
          "out_path_remote": {
            "type": "string"
          },
          "err_path_remote": {
            "type": "string"
          }
        }
      }
    }
  }
}
